In [1]:
import pandas as pd

#Listando arquivos presentes no diretório
from os import listdir
from os.path import isfile, join
path = 'tables/'

In [2]:
#consulta: https://queroficarrico.com/blog/tipos-de-fundos-imobiliarios/

#Criando novo arquivo
def new():
    
    data = {
        'id': [],
        'link': [],
        'tipo_desenvolvimento': [],
        'tipo_fof': [],
        'tipo_titulos': [],
        'tipo_hospital': [],
        'tipo_residencial': [],
        'tipo_lajes_corporativas': [],
        'tipo_shopping': [],
        'tipo_agencias_bancarias': [],
        'tipo_galpoes_logisticos': [],
        'tipo_compra_e_venda': [],
        'tipo_cri': [],
        'quantidade_ativos': [],
        'data_constituicao': [],
        'tipo_gestao': [],
        'publico_alvo': [],
        'tem_prazo': [],
        'black_list': [],
    }
    return pd.DataFrame(data)

In [3]:
#Lendo a data de hoje no sistema
from datetime import date
today = date. today()    

#Listando arquivos presentes no diretório
from os import listdir
from os.path import isfile, join
path = 'tables/'

files = [f for f in listdir(path) if isfile(join(path, f))]
if(len(files)==0):
    print('[FRX] There is no files in directory. =(')
else:
    #buscando o arquivo do dia
    try:
        filepath = [s for s in files if 'fii_'+str(today) in s][0]
    except:
        print('[FRX] There is no table today. =(')
        filepath = ''

    if(len(filepath)>0):
        import pandas as pd
        df = pd.read_csv(path+filepath)
        
        #  0 - link                     -
        #  1 - Código do fundo          -
        #  2 - Setor                    -
        #  3 - Preço Atual              -
        #  4 - Liquidez Diária          -
        #  5 - Dividendo                -
        #  6 - Dividend Yield           -
        #  7 - DY (3M) Acumulado        -
        #  8 - DY (6M) Acumulado        -
        #  9 - DY (12M) Acumulado
        # 10 - DY (3M) Média
        # 11 - DY (6M) Média
        # 12 - DY (12M) Média
        # 13 - DY Ano
        # 14 - Variação Preço
        # 15 - Rentab. Período
        # 16 - Rentab. Acumulada
        # 17 - Patrimônio Líq.
        # 18 - VPA
        # 19 - P/VPA
        # 20 - DY Patrimonial
        # 21 - Variação Patrimonial
        # 22 - Rentab. Patr. no Período
        # 23 - Rentab. Patr. Acumulada
        # 24 - Vacância Física
        # 25 - Vacância Financeira
        # 26 - Quantidade Ativos

        #Categorias
        df['Código do fundo'] = df['Código do fundo'].astype('category')
        df['link'] = df['link'].astype('category')
        df['Setor'] = df['Setor'].astype('category')
        
        #int32
        df['Quantidade Ativos'] = df['Quantidade Ativos'].astype('int32')
        
        #float64
        float_mask = [4,19]
        for f in float_mask:
            #df[df.columns[f]] = pd.to_numeric(df[df.columns[f]].str.replacece(',','.',regex=False), errors='coerce')
            df[df.columns[f]] = df[df.columns[f]].apply(lambda x: float(str(x).replace(',','.')))
        
        #moedas
        df['Preço Atual'] = pd.to_numeric(df['Preço Atual'].str.replace('.','', regex=False).str.replace("R$ ","", regex=False).str.replace(',','.',regex=False),errors='coerce')
        df['Dividendo'] = pd.to_numeric(df['Dividendo'].str.replace('.','', regex=False).str.replace("R$ ","", regex=False).str.replace(',','.',regex=False),errors='coerce')
        df['Patrimônio Líq.'] = pd.to_numeric(df['Patrimônio Líq.'].str.replace('.','', regex=False).str.replace("R$ ","", regex=False).str.replace(',','.',regex=False),errors='coerce')
        df['VPA'] = pd.to_numeric(df['VPA'].str.replace('.','', regex=False).str.replace("R$ ","", regex=False).str.replace(',','.',regex=False),errors='coerce')
        
        
        #porcentagens
        percent_mask = [6,7,8,9,10,11,12,13,14,15,16,20,21,22,23,24,25]
        
        for p in percent_mask:
            df[df.columns[p]] = pd.to_numeric(df[df.columns[p]].str.replace("%","",regex=False).str.replace(',','.',regex=False),errors='coerce')

In [4]:
df.head()

,link,Código do fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,Dividend Yield,DY (3M) Acumulado,DY (6M) Acumulado,DY (12M) Acumulado,...,Patrimônio Líq.,VPA,P/VPA,DY Patrimonial,Variação Patrimonial,Rentab. Patr. no Período,Rentab. Patr. Acumulada,Vacância Física,Vacância Financeira,Quantidade Ativos
0,/funds/bcri11,BCRI11,Títulos e Val. Mob.,131.95,3230.0,0.83,0.63,1.98,4.35,9.91,...,1.789926e+08,103.46,1.28,0.86,2.24,3.11,7.91,NaN,NaN,0
1,/funds/bnfs11,BNFS11,Outros,130.50,286.0,0.77,0.59,2.04,4.23,8.25,...,6.399823e+07,91.43,1.43,1.00,0.02,1.02,4.67,NaN,NaN,18
2,/funds/bbfi11b,BBFI11B,Lajes Corporativas,2699.00,266.0,25.71,0.95,2.72,5.79,12.98,...,3.994111e+08,3072.39,0.88,0.79,-0.01,0.78,6.04,38.59,NaN,2
3,/funds/bbpo11,BBPO11,Lajes Corporativas,151.01,47171.0,1.06,0.70,2.09,4.26,8.75,...,1.636606e+09,102.80,1.47,1.00,-0.08,0.91,6.91,0.00,NaN,64
4,/funds/bbrc11,BBRC11,Outros,135.05,4740.0,0.92,0.68,2.04,4.08,8.12,...,1.637418e+08,102.98,1.31,0.89,0.03,0.92,7.87,NaN,NaN,20

In [5]:
df_info = new()

In [6]:
df_info.head()

Empty DataFrame
Columns: [id, link, tipo_desenvolvimento, tipo_fof, tipo_titulos, tipo_hospital, tipo_residencial, tipo_lajes_corporativas, tipo_shopping, tipo_agencias_bancarias, tipo_galpoes_logisticos, tipo_compra_e_venda, tipo_cri, quantidade_ativos, data_constituicao, tipo_gestao, publico_alvo, tem_prazo, black_list]
Index: []

In [7]:
df_info.id = df['Código do fundo']
df_info.link = df['link']
df_info.quantidade_ativos = df['Quantidade Ativos']

In [8]:
df_info.tipo_hospital = df['Setor'] == 'Hospital'
df_info.tipo_residencial = df['Setor'] == 'Residencial'
df_info.tipo_lajes_corporativas = df['Setor'] == 'Lajes Corporativas'
df_info.tipo_shopping = df['Setor'] == 'Shoppings'
df_info.tipo_galpoes_logisticos = df['Setor'] == 'Logística'
df_info.tipo_titulos = df['Setor'] == 'Títulos e Val. Mob.'

In [9]:
df_info.tipo_desenvolvimento = None
df_info.tipo_agencias_bancarias = None
df_info.data_constituicao = None
df_info.tipo_gestao = None
df_info.publico_alvo = None
df_info.tem_prazo = None
df_info.tipo_fof = None
df_info.tipo_compra_e_venda = None
df_info.tipo_cri = None

In [10]:
df_info.head()

,id,link,tipo_desenvolvimento,tipo_fof,tipo_titulos,tipo_hospital,tipo_residencial,tipo_lajes_corporativas,tipo_shopping,tipo_agencias_bancarias,tipo_galpoes_logisticos,tipo_compra_e_venda,tipo_cri,quantidade_ativos,data_constituicao,tipo_gestao,publico_alvo,tem_prazo,black_list
0,BCRI11,/funds/bcri11,None,None,True,False,False,False,False,None,False,None,None,0,None,None,None,None,NaN
1,BNFS11,/funds/bnfs11,None,None,False,False,False,False,False,None,False,None,None,18,None,None,None,None,NaN
2,BBFI11B,/funds/bbfi11b,None,None,False,False,False,True,False,None,False,None,None,2,None,None,None,None,NaN
3,BBPO11,/funds/bbpo11,None,None,False,False,False,True,False,None,False,None,None,64,None,None,None,None,NaN
4,BBRC11,/funds/bbrc11,None,None,False,False,False,False,False,None,False,None,None,20,None,None,None,None,NaN

In [11]:
df_info.to_json(path+'fii_info.json')